# Generated by Django 5.0.3 on 2024-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beverages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="stars",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coffee",
            name="description",
            field=models.TextField(verbose_name="Описание кофе"),
        ),
        migrations.AlterField(
            model_name="coffee",
            name="image",
            field=models.TextField(verbose_name="Фотография кофе"),
        ),
        migrations.AlterField(
            model_name="coffee",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Название кофе"),
        ),
        migrations.AlterField(
            model_name="step",
            name="description",
            field=models.TextField(verbose_name="Описание шага"),
        ),
        migrations.AlterField(
            model_name="step",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Название шага"),
        ),
        migrations.AlterField(
            model_name="step",
            name="step_number",
            field=models.IntegerField(verbose_name="Номер шага"),
        ),
        migrations.AlterField(
            model_name="step",
            name="video",
            field=models.TextField(verbose_name="шаг"),
        ),
    ]
